name: Pull Requests

on:
  pull_request:
    branches:
      - main
      - track/**

permissions:
  contents: read
  pull-requests: write

jobs:
  pull-request:
    name: PR
    uses: canonical/observability/.github/workflows/charm-pull-request.yaml@v1
    secrets:
      CHARMHUB_TOKEN: ${{ secrets.CHARMHUB_TOKEN }}
      OBSERVABILITY_NOCTUA_TOKEN: ${{ secrets.OBSERVABILITY_NOCTUA_TOKEN || github.token }}
    with:
      provider: machine
